### ISSUE TITLE
Unable to retrieve the disclaimer text

### ISSUE THREAD

**Issue by fuglede** [SaxoBank/openapi-samples-python#2]
When I try to run the code flow script, using a SIM environment application, I'm prompted for credentials as expected, but upon passing the credentials for the corresponding SIM account, I get the error message "Unable to retrieve the disclaimer text: Token missing from request":

![image](https://user-images.githubusercontent.com/6169306/103378726-943d2980-4ae3-11eb-819b-9b2509b0d3cb.png)

The same error is displayed when running the modified script from #1.

This happens in Firefox 85.0b2 but notably not in Chrome 86.0.4240.198. I suppose the former is simply not supported? Tripped me up, since that's the one picked by `webbrowser` in my case.

**Comment by basgroot** [comment]
Hi Fuglede,

It looks like this was an issue on the SIM environment during the holidays.
Can you test again, to see if the issue has been solved?

Regards,
Bas

**Comment by fuglede** [comment]
Hi @basgroot, I just tried again (albeit in the live environment); still fails in Firefox, but still works in Chrome.
